from PyQt5 import QtCore, QtGui, QtWidgets

import sys


class Ui_StartWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 800)
        MainWindow.setMinimumSize(QtCore.QSize(600, 800))
        MainWindow.setMaximumSize(QtCore.QSize(600, 800))
        MainWindow.setStyleSheet("background-color: rgb(67, 67, 67);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_eda = QtWidgets.QLabel(self.centralwidget)
        self.label_eda.setGeometry(QtCore.QRect(210, 90, 181, 100))
        font = QtGui.QFont()
        font.setFamily("SF Collegiate")
        font.setPointSize(47)
        self.label_eda.setFont(font)
        self.label_eda.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_eda.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_eda.setObjectName("label_eda")
        self.btn_next1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_next1.setGeometry(QtCore.QRect(200, 550, 200, 61))
        self.btn_next1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(116, 116, 116);")
        self.btn_next1.setObjectName("btn_next1")
        self.label_login = QtWidgets.QLabel(self.centralwidget)
        self.label_login.setGeometry(QtCore.QRect(180, 292, 61, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_login.setObjectName("label_login")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(170, 362, 81, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_password.setFont(font)
        self.label_password.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_password.setObjectName("label_password")
        self.btn_register = QtWidgets.QPushButton(self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(235, 420, 128, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setUnderline(True)
        self.btn_register.setFont(font)
        self.btn_register.setStyleSheet("color: rgb(255, 255, 255);")
        self.btn_register.setObjectName("btn_register")
        self.login = QtWidgets.QLineEdit(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(250, 300, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login.setFont(font)
        self.login.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(250, 370, 181, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password.setObjectName("password")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Еда-фит"))
        self.label_eda.setText(_translate("MainWindow", "eda-fit"))
        self.btn_next1.setText(_translate("MainWindow", "Далее"))
        self.label_login.setText(_translate("MainWindow", "Логин:"))
        self.label_password.setText(_translate("MainWindow", "Пароль:"))
        self.btn_register.setText(_translate("MainWindow", "Зарегестрироваться"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
